# Generated by Django 3.2.9 on 2022-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('device_name', models.CharField(max_length=60)),
                ('category', models.IntegerField(choices=[(0, 'Podzespoły komputerowe'), (1, 'Monitory'), (2, 'Klawiatury i myszki'), (3, 'Dyski i nośniki danych'), (4, 'Słuchawki'), (5, 'Drukarki i skanery'), (6, 'Kable i akcesoria'), (7, 'Inne')], default=7)),
            ],
        ),
    ]
