# Generated by Django 3.2.9 on 2021-12-16 15:23

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211216_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Telefon kontaktowy', max_length=31),
        ),
    ]
