# Generated by Django 3.2.9 on 2021-12-17 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('order_state', models.IntegerField(choices=[(0, 'W trakcie weryfikacji'), (1, 'Zaakceptowano'), (2, 'W trakcie naprawy'), (3, 'Ukończono')], default=0)),
                ('description', models.CharField(default='Brak opisu', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
