# Generated by Django 3.2.9 on 2021-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_order_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
