# Generated by Django 3.2.9 on 2021-12-17 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
